// <auto-generated />
using System;
using DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(CharityDbContext))]
    partial class CharityDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataAccess.Entities.Donation", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DonorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("OrganizationId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("TimeOfOperation")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DonorId");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Donations");

                    b.HasData(
                        new
                        {
                            Id = "193f8ec5-fcf7-4b4c-96e8-6f90a14459e6",
                            Amount = 8437m,
                            DonorId = "7ec212ed-a6cd-43da-9062-51eb3565703a",
                            OrganizationId = "44724604-1138-4ef4-a6a6-8be13e5fbc05",
                            TimeOfOperation = new DateTime(2024, 5, 10, 12, 51, 21, 862, DateTimeKind.Local).AddTicks(9988)
                        },
                        new
                        {
                            Id = "8a2401a0-34ef-40bd-bcc7-b6c0be608ac3",
                            Amount = 3234m,
                            DonorId = "7ec212ed-a6cd-43da-9062-51eb3565703a",
                            OrganizationId = "e4463913-a731-4ef9-a745-6720bc719fec",
                            TimeOfOperation = new DateTime(2024, 11, 3, 12, 51, 21, 863, DateTimeKind.Local).AddTicks(249)
                        },
                        new
                        {
                            Id = "395c2870-8ff6-4ed7-8cc2-31d01e41b88f",
                            Amount = 7322m,
                            DonorId = "7ec212ed-a6cd-43da-9062-51eb3565703a",
                            OrganizationId = "143e7fda-51b1-49d6-a915-6f931ef38a1b",
                            TimeOfOperation = new DateTime(2024, 12, 2, 12, 51, 21, 863, DateTimeKind.Local).AddTicks(260)
                        },
                        new
                        {
                            Id = "68d9d9b7-8f7f-4a05-8c0a-8888c1554258",
                            Amount = 5508m,
                            DonorId = "7ec212ed-a6cd-43da-9062-51eb3565703a",
                            OrganizationId = "a7474e3f-c946-4a03-8464-d3d582bb88bc",
                            TimeOfOperation = new DateTime(2024, 3, 6, 12, 51, 21, 863, DateTimeKind.Local).AddTicks(265)
                        },
                        new
                        {
                            Id = "64bc3276-8a04-4745-b0a6-a8da0308cbee",
                            Amount = 9895m,
                            DonorId = "1ea12edd-2a72-4a41-a4c8-e90e7532e198",
                            OrganizationId = "143e7fda-51b1-49d6-a915-6f931ef38a1b",
                            TimeOfOperation = new DateTime(2024, 10, 25, 12, 51, 21, 863, DateTimeKind.Local).AddTicks(461)
                        },
                        new
                        {
                            Id = "82a7c4b6-ad23-4d85-ab19-a4bb520c1a0a",
                            Amount = 4460m,
                            DonorId = "1ea12edd-2a72-4a41-a4c8-e90e7532e198",
                            OrganizationId = "ceecc567-2fc6-48d7-a82c-c912993f5ec1",
                            TimeOfOperation = new DateTime(2024, 9, 11, 12, 51, 21, 863, DateTimeKind.Local).AddTicks(469)
                        },
                        new
                        {
                            Id = "9bc2cd1e-2fc7-40f3-af45-ceb4c729a10b",
                            Amount = 1706m,
                            DonorId = "1ea12edd-2a72-4a41-a4c8-e90e7532e198",
                            OrganizationId = "a7474e3f-c946-4a03-8464-d3d582bb88bc",
                            TimeOfOperation = new DateTime(2024, 10, 24, 12, 51, 21, 863, DateTimeKind.Local).AddTicks(474)
                        },
                        new
                        {
                            Id = "9a6b50b2-4a30-4316-ac68-7b9389b8b562",
                            Amount = 1609m,
                            DonorId = "b2fdd407-4270-4bcb-84e9-5129df7f2f66",
                            OrganizationId = "143e7fda-51b1-49d6-a915-6f931ef38a1b",
                            TimeOfOperation = new DateTime(2024, 9, 10, 12, 51, 21, 863, DateTimeKind.Local).AddTicks(528)
                        },
                        new
                        {
                            Id = "4e50059d-e524-434d-a7d9-d6d7d8ab906e",
                            Amount = 7437m,
                            DonorId = "b2fdd407-4270-4bcb-84e9-5129df7f2f66",
                            OrganizationId = "ceecc567-2fc6-48d7-a82c-c912993f5ec1",
                            TimeOfOperation = new DateTime(2024, 8, 9, 12, 51, 21, 863, DateTimeKind.Local).AddTicks(534)
                        },
                        new
                        {
                            Id = "27e719d5-0711-4f89-b34a-262f1892de07",
                            Amount = 7592m,
                            DonorId = "6adad1ca-bbd5-4206-a5de-01322ad64df9",
                            OrganizationId = "44724604-1138-4ef4-a6a6-8be13e5fbc05",
                            TimeOfOperation = new DateTime(2024, 10, 31, 12, 51, 21, 863, DateTimeKind.Local).AddTicks(587)
                        },
                        new
                        {
                            Id = "c4bcddbe-0545-4d3a-b22d-69dfb4f1edde",
                            Amount = 5946m,
                            DonorId = "6adad1ca-bbd5-4206-a5de-01322ad64df9",
                            OrganizationId = "ceecc567-2fc6-48d7-a82c-c912993f5ec1",
                            TimeOfOperation = new DateTime(2024, 4, 10, 12, 51, 21, 863, DateTimeKind.Local).AddTicks(593)
                        },
                        new
                        {
                            Id = "5f9fe36d-6371-49c8-b2e9-7ef219760ade",
                            Amount = 7786m,
                            DonorId = "23500d82-c23a-4d24-9ac7-8d1e698498f5",
                            OrganizationId = "ceecc567-2fc6-48d7-a82c-c912993f5ec1",
                            TimeOfOperation = new DateTime(2024, 10, 20, 12, 51, 21, 863, DateTimeKind.Local).AddTicks(610)
                        },
                        new
                        {
                            Id = "12e90770-8b3c-4caf-adaa-78517e63ba16",
                            Amount = 8964m,
                            DonorId = "23500d82-c23a-4d24-9ac7-8d1e698498f5",
                            OrganizationId = "143e7fda-51b1-49d6-a915-6f931ef38a1b",
                            TimeOfOperation = new DateTime(2025, 1, 19, 12, 51, 21, 863, DateTimeKind.Local).AddTicks(618)
                        },
                        new
                        {
                            Id = "4967a611-02e0-4138-b5f4-f7a2ee10a1dc",
                            Amount = 3130m,
                            DonorId = "23500d82-c23a-4d24-9ac7-8d1e698498f5",
                            OrganizationId = "e4463913-a731-4ef9-a745-6720bc719fec",
                            TimeOfOperation = new DateTime(2024, 4, 9, 12, 51, 21, 863, DateTimeKind.Local).AddTicks(623)
                        },
                        new
                        {
                            Id = "6c83f69e-24a5-41b4-b59f-969b4836f5a2",
                            Amount = 7159m,
                            DonorId = "23500d82-c23a-4d24-9ac7-8d1e698498f5",
                            OrganizationId = "44724604-1138-4ef4-a6a6-8be13e5fbc05",
                            TimeOfOperation = new DateTime(2024, 8, 28, 12, 51, 21, 863, DateTimeKind.Local).AddTicks(627)
                        },
                        new
                        {
                            Id = "6e5e4269-0d81-4bae-8607-ffc62103354f",
                            Amount = 4250m,
                            DonorId = "33d7d29c-eae3-46da-98ae-3ae5217da99e",
                            OrganizationId = "ceecc567-2fc6-48d7-a82c-c912993f5ec1",
                            TimeOfOperation = new DateTime(2025, 1, 12, 12, 51, 21, 863, DateTimeKind.Local).AddTicks(644)
                        },
                        new
                        {
                            Id = "847e6cfd-c2ab-4cf0-8f29-be2b47e4bf61",
                            Amount = 5111m,
                            DonorId = "33d7d29c-eae3-46da-98ae-3ae5217da99e",
                            OrganizationId = "44724604-1138-4ef4-a6a6-8be13e5fbc05",
                            TimeOfOperation = new DateTime(2024, 9, 9, 12, 51, 21, 863, DateTimeKind.Local).AddTicks(649)
                        },
                        new
                        {
                            Id = "6e8b78be-17a3-404e-920d-c7be9a9bb99c",
                            Amount = 5202m,
                            DonorId = "33d7d29c-eae3-46da-98ae-3ae5217da99e",
                            OrganizationId = "e4463913-a731-4ef9-a745-6720bc719fec",
                            TimeOfOperation = new DateTime(2025, 1, 30, 12, 51, 21, 863, DateTimeKind.Local).AddTicks(655)
                        },
                        new
                        {
                            Id = "4ed7555c-94b9-4c0f-9890-55df9f649f0b",
                            Amount = 2210m,
                            DonorId = "33d7d29c-eae3-46da-98ae-3ae5217da99e",
                            OrganizationId = "143e7fda-51b1-49d6-a915-6f931ef38a1b",
                            TimeOfOperation = new DateTime(2024, 5, 25, 12, 51, 21, 863, DateTimeKind.Local).AddTicks(660)
                        });
                });

            modelBuilder.Entity("DataAccess.Entities.Donor", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Donors");

                    b.HasData(
                        new
                        {
                            Id = "7ec212ed-a6cd-43da-9062-51eb3565703a",
                            Email = "donor1@mail.com",
                            Name = "Donor 1",
                            PhoneNumber = "380501000000"
                        },
                        new
                        {
                            Id = "1ea12edd-2a72-4a41-a4c8-e90e7532e198",
                            Email = "donor2@mail.com",
                            Name = "Donor 2",
                            PhoneNumber = "380502000000"
                        },
                        new
                        {
                            Id = "b2fdd407-4270-4bcb-84e9-5129df7f2f66",
                            Email = "donor3@mail.com",
                            Name = "Donor 3",
                            PhoneNumber = "380503000000"
                        },
                        new
                        {
                            Id = "6adad1ca-bbd5-4206-a5de-01322ad64df9",
                            Email = "donor4@mail.com",
                            Name = "Donor 4",
                            PhoneNumber = "380504000000"
                        },
                        new
                        {
                            Id = "23500d82-c23a-4d24-9ac7-8d1e698498f5",
                            Email = "donor5@mail.com",
                            Name = "Donor 5",
                            PhoneNumber = "380505000000"
                        },
                        new
                        {
                            Id = "33d7d29c-eae3-46da-98ae-3ae5217da99e",
                            Email = "donor6@mail.com",
                            Name = "Donor 6",
                            PhoneNumber = "380506000000"
                        });
                });

            modelBuilder.Entity("DataAccess.Entities.Funding", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("OrganizationId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("TimeOfOperation")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Fundings");

                    b.HasData(
                        new
                        {
                            Id = "a6ba75ca-d352-405c-8233-e9d2c321d867",
                            Amount = 13069m,
                            OrganizationId = "ceecc567-2fc6-48d7-a82c-c912993f5ec1",
                            ProjectId = "64500732-9a8e-4fbe-addc-b34f0c3a49e3",
                            TimeOfOperation = new DateTime(2024, 11, 30, 12, 51, 21, 860, DateTimeKind.Local).AddTicks(4802)
                        },
                        new
                        {
                            Id = "ba677f09-1189-4cf6-8932-a3c989c78ed4",
                            Amount = 2217m,
                            OrganizationId = "ceecc567-2fc6-48d7-a82c-c912993f5ec1",
                            ProjectId = "aa19feb2-f8ff-4f8c-9934-13e2fd551f4d",
                            TimeOfOperation = new DateTime(2024, 12, 4, 12, 51, 21, 862, DateTimeKind.Local).AddTicks(2769)
                        },
                        new
                        {
                            Id = "1afa9941-3456-4cb0-a6fa-276b38373536",
                            Amount = 7495m,
                            OrganizationId = "ceecc567-2fc6-48d7-a82c-c912993f5ec1",
                            ProjectId = "cc64c897-7ac9-4972-a018-9abba89aa4f9",
                            TimeOfOperation = new DateTime(2025, 2, 4, 12, 51, 21, 862, DateTimeKind.Local).AddTicks(2799)
                        },
                        new
                        {
                            Id = "d28a81d0-b036-4759-ab13-bd74cc4a10f8",
                            Amount = 17357m,
                            OrganizationId = "e4463913-a731-4ef9-a745-6720bc719fec",
                            ProjectId = "16c6ceb0-7082-4108-9e97-a8319f4a28e6",
                            TimeOfOperation = new DateTime(2024, 12, 30, 12, 51, 21, 862, DateTimeKind.Local).AddTicks(2830)
                        },
                        new
                        {
                            Id = "ae88c44d-a757-4618-9699-b5d57b884427",
                            Amount = 5730m,
                            OrganizationId = "e4463913-a731-4ef9-a745-6720bc719fec",
                            ProjectId = "19c358cc-8115-4366-b51e-895a6d1806e9",
                            TimeOfOperation = new DateTime(2025, 2, 11, 12, 51, 21, 862, DateTimeKind.Local).AddTicks(2849)
                        },
                        new
                        {
                            Id = "ddfe2604-de40-47aa-bb24-0057c77ab9ff",
                            Amount = 5925m,
                            OrganizationId = "e4463913-a731-4ef9-a745-6720bc719fec",
                            ProjectId = "30c88134-87b8-4ff0-a119-cc0cd62b44ad",
                            TimeOfOperation = new DateTime(2025, 1, 26, 12, 51, 21, 862, DateTimeKind.Local).AddTicks(2865)
                        },
                        new
                        {
                            Id = "aa991c82-6703-4f38-8658-06c8ac40cbc8",
                            Amount = 2844m,
                            OrganizationId = "143e7fda-51b1-49d6-a915-6f931ef38a1b",
                            ProjectId = "4a81d64d-bb22-4293-a372-2c29d1e1976f",
                            TimeOfOperation = new DateTime(2024, 12, 4, 12, 51, 21, 862, DateTimeKind.Local).AddTicks(2919)
                        },
                        new
                        {
                            Id = "c48a871e-797f-4191-9f5a-30223732051a",
                            Amount = 14508m,
                            OrganizationId = "143e7fda-51b1-49d6-a915-6f931ef38a1b",
                            ProjectId = "fc214fe7-8e6c-40e6-ac91-817d0ac59b1b",
                            TimeOfOperation = new DateTime(2024, 12, 16, 12, 51, 21, 862, DateTimeKind.Local).AddTicks(2934)
                        },
                        new
                        {
                            Id = "1bcb389d-46f1-43dd-b20e-fbc3c06830c1",
                            Amount = 6675m,
                            OrganizationId = "143e7fda-51b1-49d6-a915-6f931ef38a1b",
                            ProjectId = "b621ab84-05d3-45d7-aad1-2226f9251de2",
                            TimeOfOperation = new DateTime(2025, 1, 16, 12, 51, 21, 862, DateTimeKind.Local).AddTicks(2952)
                        },
                        new
                        {
                            Id = "d6307229-d3a9-4d0b-8b01-581586c15588",
                            Amount = 18300m,
                            OrganizationId = "44724604-1138-4ef4-a6a6-8be13e5fbc05",
                            ProjectId = "b1f3b002-94bd-4e5b-97a5-1708d1ae669d",
                            TimeOfOperation = new DateTime(2025, 2, 16, 12, 51, 21, 862, DateTimeKind.Local).AddTicks(2974)
                        },
                        new
                        {
                            Id = "4addfd92-1a50-4886-a6d9-fa63ef07260f",
                            Amount = 10650m,
                            OrganizationId = "44724604-1138-4ef4-a6a6-8be13e5fbc05",
                            ProjectId = "a1322056-4a6f-4397-af7c-0299bc93dd91",
                            TimeOfOperation = new DateTime(2024, 11, 30, 12, 51, 21, 862, DateTimeKind.Local).AddTicks(2989)
                        },
                        new
                        {
                            Id = "cb034b04-d2f1-4e85-baf4-64e0a0b2e66c",
                            Amount = 5616m,
                            OrganizationId = "44724604-1138-4ef4-a6a6-8be13e5fbc05",
                            ProjectId = "ad50d34f-1c0f-4744-95d6-1934238b49ef",
                            TimeOfOperation = new DateTime(2024, 12, 31, 12, 51, 21, 862, DateTimeKind.Local).AddTicks(3003)
                        },
                        new
                        {
                            Id = "1e49b078-ecbe-4570-b51d-6a3ad1a076de",
                            Amount = 6614m,
                            OrganizationId = "a7474e3f-c946-4a03-8464-d3d582bb88bc",
                            ProjectId = "eb02df2a-3280-4933-a101-2fa51c6087ff",
                            TimeOfOperation = new DateTime(2024, 12, 28, 12, 51, 21, 862, DateTimeKind.Local).AddTicks(3048)
                        },
                        new
                        {
                            Id = "5609c29c-fa00-4efd-946d-a2daa47d9eee",
                            Amount = 2845m,
                            OrganizationId = "a7474e3f-c946-4a03-8464-d3d582bb88bc",
                            ProjectId = "d05753dd-57b5-40be-a349-787cf2ff7004",
                            TimeOfOperation = new DateTime(2025, 2, 18, 12, 51, 21, 862, DateTimeKind.Local).AddTicks(3065)
                        },
                        new
                        {
                            Id = "c092fda8-64ac-4595-8c41-8adf04bcdbbd",
                            Amount = 11028m,
                            OrganizationId = "a7474e3f-c946-4a03-8464-d3d582bb88bc",
                            ProjectId = "bc16fa28-fbd1-4572-8da3-447e72272ee7",
                            TimeOfOperation = new DateTime(2025, 2, 18, 12, 51, 21, 862, DateTimeKind.Local).AddTicks(3079)
                        });
                });

            modelBuilder.Entity("DataAccess.Entities.Organization", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Organizations");

                    b.HasData(
                        new
                        {
                            Id = "ceecc567-2fc6-48d7-a82c-c912993f5ec1",
                            Address = "Street 1, City",
                            Description = "Description for Org 1",
                            Email = "org1@charity.com",
                            Name = "Organization 1",
                            PhoneNumber = "380441000000"
                        },
                        new
                        {
                            Id = "e4463913-a731-4ef9-a745-6720bc719fec",
                            Address = "Street 2, City",
                            Description = "Description for Org 2",
                            Email = "org2@charity.com",
                            Name = "Organization 2",
                            PhoneNumber = "380442000000"
                        },
                        new
                        {
                            Id = "143e7fda-51b1-49d6-a915-6f931ef38a1b",
                            Address = "Street 3, City",
                            Description = "Description for Org 3",
                            Email = "org3@charity.com",
                            Name = "Organization 3",
                            PhoneNumber = "380443000000"
                        },
                        new
                        {
                            Id = "44724604-1138-4ef4-a6a6-8be13e5fbc05",
                            Address = "Street 4, City",
                            Description = "Description for Org 4",
                            Email = "org4@charity.com",
                            Name = "Organization 4",
                            PhoneNumber = "380444000000"
                        },
                        new
                        {
                            Id = "a7474e3f-c946-4a03-8464-d3d582bb88bc",
                            Address = "Street 5, City",
                            Description = "Description for Org 5",
                            Email = "org5@charity.com",
                            Name = "Organization 5",
                            PhoneNumber = "380445000000"
                        });
                });

            modelBuilder.Entity("DataAccess.Entities.Project", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = "64500732-9a8e-4fbe-addc-b34f0c3a49e3",
                            Description = "Project 1 description",
                            Location = "Region 1",
                            Name = "Project 1 for Org 1"
                        },
                        new
                        {
                            Id = "aa19feb2-f8ff-4f8c-9934-13e2fd551f4d",
                            Description = "Project 2 description",
                            Location = "Region 2",
                            Name = "Project 2 for Org 1"
                        },
                        new
                        {
                            Id = "cc64c897-7ac9-4972-a018-9abba89aa4f9",
                            Description = "Project 3 description",
                            Location = "Region 3",
                            Name = "Project 3 for Org 1"
                        },
                        new
                        {
                            Id = "16c6ceb0-7082-4108-9e97-a8319f4a28e6",
                            Description = "Project 1 description",
                            Location = "Region 1",
                            Name = "Project 1 for Org 2"
                        },
                        new
                        {
                            Id = "19c358cc-8115-4366-b51e-895a6d1806e9",
                            Description = "Project 2 description",
                            Location = "Region 2",
                            Name = "Project 2 for Org 2"
                        },
                        new
                        {
                            Id = "30c88134-87b8-4ff0-a119-cc0cd62b44ad",
                            Description = "Project 3 description",
                            Location = "Region 3",
                            Name = "Project 3 for Org 2"
                        },
                        new
                        {
                            Id = "4a81d64d-bb22-4293-a372-2c29d1e1976f",
                            Description = "Project 1 description",
                            Location = "Region 1",
                            Name = "Project 1 for Org 3"
                        },
                        new
                        {
                            Id = "fc214fe7-8e6c-40e6-ac91-817d0ac59b1b",
                            Description = "Project 2 description",
                            Location = "Region 2",
                            Name = "Project 2 for Org 3"
                        },
                        new
                        {
                            Id = "b621ab84-05d3-45d7-aad1-2226f9251de2",
                            Description = "Project 3 description",
                            Location = "Region 3",
                            Name = "Project 3 for Org 3"
                        },
                        new
                        {
                            Id = "b1f3b002-94bd-4e5b-97a5-1708d1ae669d",
                            Description = "Project 1 description",
                            Location = "Region 1",
                            Name = "Project 1 for Org 4"
                        },
                        new
                        {
                            Id = "a1322056-4a6f-4397-af7c-0299bc93dd91",
                            Description = "Project 2 description",
                            Location = "Region 2",
                            Name = "Project 2 for Org 4"
                        },
                        new
                        {
                            Id = "ad50d34f-1c0f-4744-95d6-1934238b49ef",
                            Description = "Project 3 description",
                            Location = "Region 3",
                            Name = "Project 3 for Org 4"
                        },
                        new
                        {
                            Id = "eb02df2a-3280-4933-a101-2fa51c6087ff",
                            Description = "Project 1 description",
                            Location = "Region 1",
                            Name = "Project 1 for Org 5"
                        },
                        new
                        {
                            Id = "d05753dd-57b5-40be-a349-787cf2ff7004",
                            Description = "Project 2 description",
                            Location = "Region 2",
                            Name = "Project 2 for Org 5"
                        },
                        new
                        {
                            Id = "bc16fa28-fbd1-4572-8da3-447e72272ee7",
                            Description = "Project 3 description",
                            Location = "Region 3",
                            Name = "Project 3 for Org 5"
                        });
                });

            modelBuilder.Entity("DataAccess.Entities.Report", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("AdministrativeSpending")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LabourSpending")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MaterialsSpending")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .IsUnique();

                    b.ToTable("Reports");

                    b.HasData(
                        new
                        {
                            Id = "603cb07b-2679-4f03-ac32-764730f2aac2",
                            AdministrativeSpending = 1968m,
                            LabourSpending = 7213m,
                            MaterialsSpending = 3362m,
                            ProjectId = "64500732-9a8e-4fbe-addc-b34f0c3a49e3"
                        },
                        new
                        {
                            Id = "31e0c7af-6b73-417a-bfdb-f89bdb7e23e7",
                            AdministrativeSpending = 1796m,
                            LabourSpending = 4447m,
                            MaterialsSpending = 4188m,
                            ProjectId = "aa19feb2-f8ff-4f8c-9934-13e2fd551f4d"
                        },
                        new
                        {
                            Id = "1c93aae3-eee9-449c-a41e-ccb6804ba205",
                            AdministrativeSpending = 1194m,
                            LabourSpending = 6100m,
                            MaterialsSpending = 5650m,
                            ProjectId = "cc64c897-7ac9-4972-a018-9abba89aa4f9"
                        },
                        new
                        {
                            Id = "ea0d96a0-19ed-4f85-a5d6-e18658301d3f",
                            AdministrativeSpending = 2111m,
                            LabourSpending = 6265m,
                            MaterialsSpending = 3058m,
                            ProjectId = "16c6ceb0-7082-4108-9e97-a8319f4a28e6"
                        },
                        new
                        {
                            Id = "7c48b796-86c8-4192-a37d-688d08f429af",
                            AdministrativeSpending = 1507m,
                            LabourSpending = 6515m,
                            MaterialsSpending = 6871m,
                            ProjectId = "19c358cc-8115-4366-b51e-895a6d1806e9"
                        },
                        new
                        {
                            Id = "1db57be7-7497-44c6-8bcc-9212220813ea",
                            AdministrativeSpending = 1278m,
                            LabourSpending = 4236m,
                            MaterialsSpending = 4299m,
                            ProjectId = "30c88134-87b8-4ff0-a119-cc0cd62b44ad"
                        },
                        new
                        {
                            Id = "9c5b84f5-2ba1-4463-b07a-2cb2fa58eabd",
                            AdministrativeSpending = 1541m,
                            LabourSpending = 6871m,
                            MaterialsSpending = 5933m,
                            ProjectId = "4a81d64d-bb22-4293-a372-2c29d1e1976f"
                        },
                        new
                        {
                            Id = "c617d7d8-20cb-45e6-a6d5-a761372bec74",
                            AdministrativeSpending = 1860m,
                            LabourSpending = 5314m,
                            MaterialsSpending = 6732m,
                            ProjectId = "fc214fe7-8e6c-40e6-ac91-817d0ac59b1b"
                        },
                        new
                        {
                            Id = "cd73c60f-d53c-483e-b22f-a7d8dbb97a78",
                            AdministrativeSpending = 2984m,
                            LabourSpending = 5336m,
                            MaterialsSpending = 4539m,
                            ProjectId = "b621ab84-05d3-45d7-aad1-2226f9251de2"
                        },
                        new
                        {
                            Id = "f3abeaf4-7c08-4e34-87aa-ce53bb3ce088",
                            AdministrativeSpending = 4846m,
                            LabourSpending = 3673m,
                            MaterialsSpending = 2347m,
                            ProjectId = "b1f3b002-94bd-4e5b-97a5-1708d1ae669d"
                        },
                        new
                        {
                            Id = "8a33a0a3-0245-4b42-8502-ec726053f36d",
                            AdministrativeSpending = 4351m,
                            LabourSpending = 6228m,
                            MaterialsSpending = 3944m,
                            ProjectId = "a1322056-4a6f-4397-af7c-0299bc93dd91"
                        },
                        new
                        {
                            Id = "f37448b0-be9b-4d75-918a-23e51228ca58",
                            AdministrativeSpending = 4014m,
                            LabourSpending = 5853m,
                            MaterialsSpending = 5619m,
                            ProjectId = "ad50d34f-1c0f-4744-95d6-1934238b49ef"
                        },
                        new
                        {
                            Id = "1aa22666-8871-4bde-866b-8b5e956d2612",
                            AdministrativeSpending = 1522m,
                            LabourSpending = 3336m,
                            MaterialsSpending = 2623m,
                            ProjectId = "eb02df2a-3280-4933-a101-2fa51c6087ff"
                        },
                        new
                        {
                            Id = "deda7dc2-6a46-41eb-a19b-971de781c02c",
                            AdministrativeSpending = 3647m,
                            LabourSpending = 5086m,
                            MaterialsSpending = 3318m,
                            ProjectId = "d05753dd-57b5-40be-a349-787cf2ff7004"
                        },
                        new
                        {
                            Id = "d91ec204-7227-483e-be58-6e554a5e5b9d",
                            AdministrativeSpending = 2221m,
                            LabourSpending = 3824m,
                            MaterialsSpending = 6630m,
                            ProjectId = "bc16fa28-fbd1-4572-8da3-447e72272ee7"
                        });
                });

            modelBuilder.Entity("DataAccess.Entities.Donation", b =>
                {
                    b.HasOne("DataAccess.Entities.Donor", "Donor")
                        .WithMany("Donations")
                        .HasForeignKey("DonorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccess.Entities.Organization", "Organization")
                        .WithMany("Donations")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Donor");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("DataAccess.Entities.Funding", b =>
                {
                    b.HasOne("DataAccess.Entities.Organization", "Organization")
                        .WithMany("Fundings")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccess.Entities.Project", "Project")
                        .WithMany("Fundings")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("DataAccess.Entities.Report", b =>
                {
                    b.HasOne("DataAccess.Entities.Project", "Project")
                        .WithOne("Report")
                        .HasForeignKey("DataAccess.Entities.Report", "ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("DataAccess.Entities.Donor", b =>
                {
                    b.Navigation("Donations");
                });

            modelBuilder.Entity("DataAccess.Entities.Organization", b =>
                {
                    b.Navigation("Donations");

                    b.Navigation("Fundings");
                });

            modelBuilder.Entity("DataAccess.Entities.Project", b =>
                {
                    b.Navigation("Fundings");

                    b.Navigation("Report");
                });
#pragma warning restore 612, 618
        }
    }
}
